"""
Transcription Service — DemoBank Loan Application Asset
Multimodal PDF transcription using Watsonx.ai Vision models.

Handles both:
  - Scanned PDFs / mobile photos (via Mistral vision model)
  - Digital PDFs with embedded text (via PyMuPDF, free, instant)

Includes MD5-based disk cache to avoid re-transcribing the same document.

PDF→Image rendering uses PyMuPDF (fitz) instead of pdf2image/Poppler.
fitz produces sharper renders with correct antialiasing at all DPI values,
which is critical for Mistral Vision to correctly read the text.
"""

import io
import base64
import hashlib
import os
import requests
import fitz          # PyMuPDF — also used for PDF→image rendering
from PIL import Image
from dotenv import load_dotenv

load_dotenv()

# ---------------------------------------------------------------------------
#  Disk cache keyed by MD5 of PDF bytes
# ---------------------------------------------------------------------------

# Each asset has its own isolated cache directory to avoid cross-contamination
# with other assets sharing the same parent repo.
# NOTE: resolved at call time (not import time) so __file__ is always correct
# regardless of the working directory the server is launched from.
def _cache_dir() -> str:
    d = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        ".transcription_cache",
    )
    os.makedirs(d, exist_ok=True)
    return d


def _cache_key(pdf_bytes: bytes) -> str:
    return hashlib.md5(pdf_bytes).hexdigest()


def _get_cached(pdf_bytes: bytes) -> str | None:
    path = os.path.join(_cache_dir(), f"{_cache_key(pdf_bytes)}.txt")
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            return f.read()
    return None


def _save_cache(pdf_bytes: bytes, text: str) -> None:
    path = os.path.join(_cache_dir(), f"{_cache_key(pdf_bytes)}.txt")
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)


# ---------------------------------------------------------------------------
#  IBM IAM Authentication
# ---------------------------------------------------------------------------

def get_iam_token(api_key: str = None) -> str:
    """Exchange an IBM Cloud API Key for a Bearer IAM token."""
    api_key = api_key or os.getenv("WATSONX_API_KEY")
    url = "https://iam.cloud.ibm.com/identity/token"
    headers = {"Content-Type": "application/x-www-form-urlencoded"}
    data = f"grant_type=urn:ibm:params:oauth:grant-type:apikey&apikey={api_key}"
    response = requests.post(url, headers=headers, data=data)
    if response.status_code == 200:
        return response.json()["access_token"]
    raise Exception(f"Failed to get IAM token: {response.text}")


# ---------------------------------------------------------------------------
#  Option A: Digital PDF — PyMuPDF (no AI, instant, free)
# ---------------------------------------------------------------------------

def extract_text_from_pdf_bytes(pdf_bytes: bytes) -> dict:
    """
    Extract embedded text from a digital PDF using PyMuPDF (fitz).
    No AI involved — instant and free. Works well for system-generated PDFs
    (e.g. payslips generated by RRHH software).

    Returns:
        dict with keys: text, page_count, extraction_method, chars_extracted, success
    """
    try:
        import fitz  # PyMuPDF

        doc = fitz.open(stream=pdf_bytes, filetype="pdf")
        page_count = len(doc)
        pages = []
        for i, page in enumerate(doc):
            text = page.get_text("text")
            if text.strip():
                pages.append(f"--- Página {i + 1} ---\n{text}")
        doc.close()

        extracted = "\n\n".join(pages)
        return {
            "text": extracted,
            "page_count": page_count,
            "extraction_method": "pymupdf",
            "chars_extracted": len(extracted),
            "success": True,
        }
    except Exception as e:
        return {
            "text": "",
            "page_count": 0,
            "extraction_method": "pymupdf",
            "error": str(e),
            "success": False,
        }


# ---------------------------------------------------------------------------
#  Option B: Scanned/Photo PDF — Mistral Vision (AI, per-page)
# ---------------------------------------------------------------------------

def transcribe_pdf_from_bytes(
    pdf_bytes: bytes,
    api_key: str = None,
    project_id: str = None,
    model_id: str = "mistralai/mistral-medium-2505",
    url: str = None,
    dpi: int = 200,
    progress_callback=None,
) -> str:
    """
    Transcribe a scanned / photo PDF using Watsonx.ai Mistral Vision.

    Each page is:
      1. Converted to JPEG image at `dpi` resolution
      2. Encoded as Base64
      3. Sent to Mistral via the Watsonx.ai chat API
      4. The transcribed text is collected and joined

    Results are cached to disk by MD5 hash of the PDF bytes so that
    identical documents are never re-transcribed.

    Args:
        pdf_bytes:         Raw PDF file bytes.
        api_key:           IBM Cloud API Key (defaults to WATSONX_API_KEY env var).
        project_id:        Watsonx.ai project ID (defaults to WATSONX_PROJECT_ID env var).
        model_id:          Vision model to use.
        url:               Watsonx.ai base URL.
        dpi:               Resolution for PDF→image conversion (200 is a good default).
        progress_callback: Optional fn(step: str, detail: str) for SSE progress events.

    Returns:
        Full transcription as a single string (pages separated by blank lines).
    """
    # --- Cache check ---
    cached = _get_cached(pdf_bytes)
    if cached:
        print("📦 Using cached transcription")
        if progress_callback:
            progress_callback("cached", "Transcripción encontrada en cache")
        return cached

    api_key = api_key or os.getenv("WATSONX_API_KEY")
    project_id = project_id or os.getenv("WATSONX_PROJECT_ID")
    url = url or os.getenv("WATSONX_URL", "https://us-south.ml.cloud.ibm.com")

    # Convert PDF to images using PyMuPDF (fitz) — sharper than Poppler/pdf2image
    print("Converting PDF to images (fitz)...")
    doc = fitz.open(stream=pdf_bytes, filetype="pdf")
    total_pages = len(doc)
    print(f"Processing {total_pages} pages...")

    access_token = get_iam_token(api_key)
    api_url = f"{url}/ml/v1/text/chat?version=2023-05-29"

    full_transcription = []

    for i in range(total_pages):
        print(f"Transcribing page {i + 1}/{total_pages}...")
        if progress_callback:
            progress_callback("transcribing", f"Transcribiendo página {i + 1} de {total_pages}")

        # Render page to image using fitz matrix (dpi/72 scale factor)
        page = doc[i]
        mat  = fitz.Matrix(dpi / 72, dpi / 72)
        pix  = page.get_pixmap(matrix=mat, alpha=False)
        img  = Image.frombytes("RGB", [pix.width, pix.height], pix.samples)

        # Cap at 2000px on the longest side to stay within Mistral's input limits
        if max(img.size) > 2000:
            ratio = 2000 / max(img.size)
            img = img.resize(
                (int(img.width * ratio), int(img.height * ratio)),
                Image.Resampling.LANCZOS,
            )

        buffered = io.BytesIO()
        img.save(buffered, format="JPEG", quality=90)
        img_b64 = base64.b64encode(buffered.getvalue()).decode("utf-8")

        payload = {
            "messages": [
                {
                    "role": "system",
                    "content": (
                        "Eres un asistente de transcripción preciso. Tu única tarea es "
                        "transcribir el texto de la imagen proporcionada.\n\n"
                        "REGLAS:\n"
                        "1. Transcribe TODO el texto visible, sin resumir ni interpretar.\n"
                        "2. NO inventes texto que no está en la imagen.\n"
                        "3. NO repitas líneas ni entres en bucles.\n"
                        "4. Si la imagen contiene tablas o columnas de números (como un recibo de sueldo), "
                        "mantené cada fila en una línea separada.\n"
                        "5. Para documentos de identidad (DNI), transcribí cada campo en su propia línea.\n"
                        "6. Al terminar de leer la página, detente INMEDIATAMENTE.\n\n"
                        "IMPORTANTE: Si hay sellos o marcas de agua, transcribí el texto legible. "
                        "Si no hay más texto, termina."
                    ),
                },
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "text",
                            "text": f"Transcribí esta página (Página {i + 1}).",
                        },
                        {
                            "type": "image_url",
                            "image_url": {"url": f"data:image/jpeg;base64,{img_b64}"},
                        },
                    ],
                },
            ],
            "project_id": project_id,
            "model_id": model_id,
            "decoding_method": "greedy",
            "max_tokens": 3000,
            "min_tokens": 1,
            "temperature": 0,
            "repetition_penalty": 1.2,
            "stop_sequences": ["<|eot_id|>", "<|end_of_text|>", "\n\n\n\n", "## FIN"],
        }

        headers = {
            "Content-Type": "application/json",
            "Accept": "application/json",
            "Authorization": f"Bearer {access_token}",
        }

        try:
            response = requests.post(api_url, json=payload, headers=headers, timeout=300)
            if response.status_code == 200:
                content = response.json()["choices"][0]["message"]["content"]
                full_transcription.append(content)
                usage = response.json().get("usage", {})
                print(
                    f"Page {i + 1} done. Tokens: {usage.get('total_tokens', '?')} "
                    f"(prompt: {usage.get('prompt_tokens', '?')}, "
                    f"completion: {usage.get('completion_tokens', '?')})"
                )
            else:
                print(f"Error on page {i + 1}: {response.text}")
                full_transcription.append(f"[Error leyendo página {i + 1}]")
        except Exception as e:
            print(f"Exception on page {i + 1}: {e}")
            full_transcription.append(f"[Excepción en página {i + 1}: {e}]")

    result_text = "\n\n".join(full_transcription)
    _save_cache(pdf_bytes, result_text)
    print(f"💾 Transcription cached ({_cache_key(pdf_bytes)[:8]}...)")
    return result_text


# ---------------------------------------------------------------------------
#  Utility
# ---------------------------------------------------------------------------

def get_page_count_from_bytes(pdf_bytes: bytes, dpi: int = 72) -> int:
    """Return the number of pages in a PDF without full conversion."""
    try:
        doc = fitz.open(stream=pdf_bytes, filetype="pdf")
        count = len(doc)
        doc.close()
        return count
    except Exception:
        return 0
